# Generated by Django 2.1.2 on 2018-10-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openhumans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_client_id', models.CharField(max_length=512)),
                ('personal_client_secret', models.CharField(max_length=512)),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('expires_in', models.CharField(max_length=512)),
                ('scope', models.CharField(max_length=512)),
                ('token_type', models.CharField(max_length=512)),
                ('oh_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember')),
            ],
        ),
    ]
