# Generated by Django 2.1.2 on 2018-10-17 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181017_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='oh_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember'),
        ),
    ]
