# Generated by Django 2.2.6 on 2020-07-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0001_initial'),
        ('main', '0005_auto_20181017_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetatmoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=512)),
                ('refresh_token', models.CharField(default='', max_length=512)),
                ('expires_in', models.DateTimeField()),
                ('scope', models.CharField(default='', max_length=512)),
                ('oh_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember')),
            ],
        ),
    ]
