# Generated by Django 3.0.8 on 2022-02-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0002_openhumansmember_oh_deauth'),
        ('main', '0006_netatmouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=256)),
                ('oh_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember')),
            ],
        ),
    ]
