# Generated by Django 3.0.8 on 2022-02-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0002_openhumansmember_oh_deauth'),
        ('main', '0007_lastfmuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastfmuser',
            name='oh_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember'),
        ),
    ]
