# Generated by Django 2.2.28 on 2023-02-03 15:30

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0002_openhumansmember_oh_deauth'),
        ('main', '0008_auto_20220203_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleHealthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_token', models.CharField(default=main.models.generate_endpoint_token, max_length=36, unique=True)),
                ('oh_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember')),
            ],
        ),
    ]
