# Generated by Django 2.2.28 on 2024-05-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0002_openhumansmember_oh_deauth'),
        ('main', '0009_applehealthuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookwyrmHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=256)),
                ('oh_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember')),
            ],
        ),
    ]
